Refatoração em juros, multa e desconto!
imobanco/zoop-wrapper pull request #106
Opened 2020-09-10 17:11 UTC by rodrigondec

2020-09-10 18:36 UTC, PedroRegisPOAR requested changes

2020-09-10 18:36 UTC, rodrigondec commented on examples/transaction/add_transaction_invoice.py
> +pre_vencimento = "2020-11-10"
Pensei nisso hj tbm :rofl:

2020-09-10 18:58 UTC, rodrigondec commented on zoop_wrapper/models/invoice.py
> +        if mode not in self.MODES:
Exato

2020-09-10 19:00 UTC, rodrigondec commented on tests/factories/invoice.py
>      Invoice,
Ordenado!

2020-09-10 19:16 UTC, PedroRegisPOAR submitted a review, later dismissed

2020-09-11 20:14 UTC, PedroRegisPOAR requested changes

2020-09-11 20:14 UTC, PedroRegisPOAR commented on Makefile
> +	pip install -U -r requirements-dev.txt
Eu entendo a comodidade de fazer upgrade dessa forma, mas é, um dia isso vai quebrar pq vai ser feito um update de algo que quebre compatibilidade. Pq exatamente vc precisou fazer isso?

2020-09-11 20:14 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +    def test_init_custom_fields_2(self):
BDD

2020-09-11 20:14 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +    def test_init_custom_fields_3(self):
BDD

2020-09-11 20:14 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +    def test_init_custom_fields_4(self):
BDD

2020-09-11 20:15 UTC, rodrigondec commented on Makefile
> +	pip install -U -r requirements-dev.txt
Só por causa do black. No caso, a gente tem que pinar as versões (como já estão) das coisas que não podem atualizar de qualquer jeito

2020-09-11 20:34 UTC, PedroRegisPOAR requested changes

2020-09-11 20:34 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +        Quando for inicializado os campos:
```suggestion
        Quando forem inicializados os campos:
```

2020-09-11 20:34 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +        Quando for inicializado os campos:
```suggestion
        Quando forem inicializados os campos:
```

2020-09-11 20:34 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +        Quando for inicializado os campos:
```suggestion
        Quando forem inicializados os campos:
```

2020-09-11 20:34 UTC, PedroRegisPOAR commented on tests/models/invoice/test_billing_instructions.py
> +        Quando for inicializado os campos:
```suggestion
        Quando forem inicializados os campos:
```

2020-09-12 01:37 UTC, PedroRegisPOAR submitted a review, later dismissed

2020-09-14 13:46 UTC, PedroRegisPOAR approved these changes

2020-09-14 16:38 UTC, merged